--- 
- name: Add a user
  hosts: all
  gather_facts: no

  tasks:
  - name: Add a user
    user:
     name: "{{uname}}"
     state: present

  - name: get outut
    shell: "grep -E 'sahil|suri' /etc/passwd"
    register: result
 
  - name: display output
    debug:
     var: result.stdout_lines
