--- 
- name: Add a user
  hosts: centos
  gather_facts: no

  tasks:
  - name: Use include_vars module
    include_vars:
     file: vars.yaml

  - name: Add a user
    user:
     name: "{{uname}}"
     state: present

  - name: get outut
    shell: "grep -E 'sahil|suri' /etc/passwd"
    register: result
 
  - name: display output
    debug:
     var: result.stdout_lines
