--- 
- name: Add a user
  hosts: all
  gather_facts: no
  vars_files:
   vars/user.yaml

  tasks:
  - name: Add a user
    user:
     name: "{{uname}}"
     state: absent

  - name: get outut
    command: grep sahil /etc/passwd
    register: result
 
  - name: display output
    debug:
     msg: "{{result.stdout_lines}}"
